<%@ Page Title="Test Master Add/Update" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="TestCaseTestMasterAddUpdate.aspx.vb" Inherits="TestCaseTestMasterAddUpdate" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<%--<asp:Content ID="Content1" ContentPlaceHolderID="Head1" runat="Server">
</asp:Content>--%>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <%--<script type="text/javascript" src="Scripts/ValidateTestCaseTestMasterAddUpdate.js?key="&<%= DateTime.Now.ToString %>></script>--%>
    <script type="text/javascript">
        document.onkeydown = checkValue;
        function checkValue() {
            if (event.keyCode == 118) { // button Add (F7 keypress)
                __doPostBack(document.getElementById('imgbtnAdd').name, '');
            }
            else if (event.keyCode == 119) {
                __doPostBack(document.getElementById('imgbtnSearch').name, '');
            }
        }

        function disableBackButton() {
            window.history.forward(1);
        }

        function oninputDecimal(ctrl) {
            ctrl.value = ctrl.value.replace(/[^0-9.]/g, '').replace(/(\..*?)\..*/g, '$1');
        }
    </script>

    <div class="breadcrumbs">
        <div class="leftFung">
            <a href="Home.aspx" title="Home"><i class="fas fa-home"></i></a>
            <div class="diveider">/</div>
            <div class="pageTitleWrap">
                <h3 class="pageTitle">Test Case Master Add/Update</h3>
                <p class="pageSubTitle">Create and maintain quality test cases</p>
            </div>
        </div>
        <div class="rightFung"></div>
    </div>

    <div class="card">
        <div class="card-body">
            <asp:UpdatePanel ID="UpdatePanel2" runat="server">
                <ContentTemplate>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Requisition Id:</label>
                                <asp:Label runat="server" ID="lblReqId" CssClass="labelDataPoint">Autogenerated</asp:Label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Test Name:</label>
                                <asp:TextBox ID="txtTestName" runat="server" CssClass="form-control"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Frequency:</label>
                                <asp:DropDownList ID="ddlFrequency" CssClass="form-control select2" runat="server" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Result Type:</label>
                                <asp:DropDownList ID="ddlResultType" CssClass="form-control select2" runat="server" AutoPostBack="True" />
                            </div>
                        </div>
                        <div runat="server" id="pnlTypeValue" class="col-md-12">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="form-control-label">Sub Type:</label>
                                        <asp:DropDownList ID="ddlResultSubType" CssClass="form-control select2" runat="server" AutoPostBack="True" />
                                    </div>
                                </div>
                                <div class="col-md-3" runat="server" id="divTypeValue" visible="false">
                                    <div class="form-group">
                                        <label class="form-control-label">Value:</label>
                                        <asp:TextBox ID="txtTypeValue" placeholder="0" CssClass="form-control" runat="server" oninput="return oninputDecimal(this);"></asp:TextBox>
                                    </div>
                                </div>
                                <div class="col-md-3" runat="server" id="divMinValue" visible="false">
                                    <div class="form-group">
                                        <label class="form-control-label">Min Value:</label>
                                        <asp:TextBox ID="txtMinValue" placeholder="0" CssClass="form-control" runat="server" oninput="return oninputDecimal(this);"></asp:TextBox>
                                    </div>
                                </div>
                                <div class="col-md-3" runat="server" id="divMaxValue" visible="false">
                                    <div class="form-group">
                                        <label class="form-control-label">Max Value:</label>
                                        <asp:TextBox ID="txtMaxValue" placeholder="0" CssClass="form-control" runat="server" oninput="return oninputDecimal(this);"></asp:TextBox>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="form-control-label">UOM:</label>
                                        <%--<asp:DropDownList ID="ddlUOM" Font-Names="Verdana" class="form-control" runat="server" />--%>
                                        <asp:TextBox ID="txtUOM" placeholder="" CssClass="form-control" runat="server"></asp:TextBox>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div runat="server" id="pnlTypeOption" class="col-md-12">
                            <div class="row">
                                <div class="col-md-3" runat="server">
                                    <div class="form-group">
                                        <label class="form-control-label">Result Type Option:</label>
                                        <div class="groupInputBtn">
                                            <asp:TextBox ID="txtResultTypeOption" runat="server" class="form-control"></asp:TextBox>
                                            <asp:Button ID="imgbtnAdd" runat="server" Text="Add" CssClass="btn btn-success btn-sm ml-1" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12" runat="server">
                                    <div class="table-responsive">
                                        <asp:GridView ID="gvResultTypeOption" runat="server" AutoGenerateColumns="false" AllowPaging="false"
                                            Visible="true" GridLines="both" EmptyDataText="There are No Data..." BorderWidth="1" CssClass="table table-hover upgradDataGrid">
                                            <RowStyle CssClass="tlrowlight" />
                                            <PagerStyle CssClass="PagerGrid" HorizontalAlign="Right" />
                                            <HeaderStyle CssClass="headerGrid" />
                                            <FooterStyle CssClass="footerGrid" />
                                            <Columns>
                                                <asp:TemplateField HeaderText="Options" HeaderStyle-HorizontalAlign="Center">
                                                    <ItemTemplate>
                                                        <asp:HiddenField runat="server" ID="hdnTypeOptionId" Value='<%# Bind("td_dtl_id") %>' />
                                                        <asp:Label ID="lblTypeOption" runat="server" Text='<%# Bind("td_option") %>'></asp:Label>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="#" HeaderStyle-HorizontalAlign="Center" HeaderStyle-Width="25px">
                                                    <ItemTemplate>
                                                        <asp:ImageButton ID="btnEdit" CommandName="trash" runat="server" ImageUrl="~/Images/ic_delete.gif" />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                            </Columns>
                                        </asp:GridView>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 text-center">
                        <asp:UpdatePanel runat="server">
                            <ContentTemplate>
                                <asp:Button ID="btnSubmit" runat="server" Text="Submit" CssClass="btn btn-primary btn-sm" />
                                <asp:Button ID="btnCancel" runat="server" Text="Cancel" PostBackUrl="~/TestCaseTestMasterList.aspx" CssClass="btn btn-secondary btn-sm" />
                            </ContentTemplate>
                            <Triggers>
                                <asp:PostBackTrigger ControlID="btnSubmit" />
                            </Triggers>
                        </asp:UpdatePanel>
                    </div>
                    <asp:Label ID="lblErrorMessage" CssClass="errormsg" Visible="true" runat="server"></asp:Label>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
    </div>
</asp:Content>
