<%@ Page Title="Token Vendor Add/Update" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="TokenVendorAddUpdate.aspx.vb" Inherits="TokenVendorAddUpdate" %>


<%--<asp:Content ID="Content1" ContentPlaceHolderID="Head1" runat="Server">
</asp:Content>--%>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    

    <script type="text/javascript" src="Scripts/ValidateTokenVendorAddUpdate.js?key="&<%= DateTime.Now.ToString %>""></script>
    <script type="text/javascript">
        document.onkeydown = checkValue;
        function checkValue() {
            if (event.keyCode == 118) { // button Add (F7 keypress)
                __doPostBack(document.getElementById('imgbtnAdd').name, '');
            }
            else if (event.keyCode == 119) {
                __doPostBack(document.getElementById('imgbtnSearch').name, '');
            }
        }

        function disableBackButton() {
            window.history.forward(1);
        }
    </script>

    <div class="breadcrumbs">
        <div class="leftFung">
            <a href="Home.aspx" title="Home"><i class="fas fa-home"></i></a>
            <div class="diveider">/</div>
            <div class="pageTitleWrap">
                <h3 class="pageTitle">Token Vendor Add/Update</h3>
                <p class="pageSubTitle">Create and maintain token vendor records</p>
            </div>
        </div>
        <div class="rightFung"></div>
    </div>

    <asp:UpdatePanel ID="UpdatePanel2" runat="server">
        <ContentTemplate>
            <div class="card">
                <div class="card-body">
                    <asp:Label ID="lblErrorMessage" CssClass="errormsg" Visible="true" runat="server"></asp:Label>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Vendor Id:</label>
                                <asp:Label runat="server" ID="lblVendorId" CssClass="labelDataPoint">**Autogenerated**</asp:Label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Token Vendor Name:<span id="Span9" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtTokenVendorName" CssClass="form-control" runat="server" MaxLength="50"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Token Vendor Email:<span id="Span1" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtTokenVendorEmail" CssClass="form-control" runat="server" MaxLength="200"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Token Vendor Mobile:<span id="Span2" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtMobile" CssClass="form-control" runat="server" MaxLength="10"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-control-label">Token Vendor Address:<span id="Span3" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtAddress" CssClass="form-control" TextMode="MultiLine" runat="server" MaxLength="500"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Token Vendor City:<span id="Span4" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtCity" CssClass="form-control" runat="server" MaxLength="100"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Token Vendor State:<span id="Span5" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtState" CssClass="form-control" runat="server" MaxLength="50"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="form-control-label">Zip Code:<span id="Span6" class="mandatory">*</span></label>
                                <asp:TextBox ID="txtZip" CssClass="form-control" runat="server" MaxLength="50"></asp:TextBox>
                            </div>
                        </div>
                        <div class="col-md-3" id="trActive" runat="server" visible="false">
                            <div class="form-group">
                                <label class="form-control-label">Active:<span id="Span7" class="mandatory">*</span></label>
                                <asp:DropDownList ID="ddlActive" runat="server" CssClass="form-control select2">
                                    <asp:ListItem Value="" Selected="True">Select</asp:ListItem>
                                    <asp:ListItem Value="Y">Yes</asp:ListItem>
                                    <asp:ListItem Value="N">No</asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                        <div class="col-md-3 form-btn-mt">
                            <div class="form-group">
                                <asp:Button ID="btnSubmit" runat="server" Text="Submit" CssClass="btn btn-success btn-sm" />
                                <asp:Button ID="btnCancel" runat="server" Text="Cancel" CssClass="btn btn-secondary btn-sm" PostBackUrl="~/TokenVendorList.aspx" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
